export interface MetricConfig {
	key: string;
	displayName: string;
	singular: string;
	plural: string;
	aliases: string[];
	description: string;
}

export const metricConfigs: MetricConfig[] = [
	{
		key: "APP",
		displayName: "appearances",
		singular: "appearance",
		plural: "appearances",
		aliases: ["apps", "games", "matches", "games played", "matches played"],
		description: "Number of games/matches played",
	},
	{
		key: "MIN",
		displayName: "minutes",
		singular: "minute played",
		plural: "minutes played",
		aliases: ["minutes", "mins", "time played", "playing time"],
		description: "Total minutes played",
	},
	{
		key: "MOM",
		displayName: "man of the match",
		singular: "man of the match award",
		plural: "man of the match awards",
		aliases: ["mom", "man of match", "star man", "player of match", "best player"],
		description: "Man of the match awards",
	},
	{
		key: "G",
		displayName: "goals",
		singular: "goal",
		plural: "goals",
		aliases: ["goal", "scored", "scoring", "strikes"],
		description: "Goals scored",
	},
	{
		key: "A",
		displayName: "assists",
		singular: "assist",
		plural: "assists",
		aliases: ["assist", "assisting", "set up", "setup"],
		description: "Assists provided",
	},
	{
		key: "Y",
		displayName: "yellow cards",
		singular: "yellow card",
		plural: "yellow cards",
		aliases: ["yellow", "yellows", "booking", "bookings", "caution", "cautions"],
		description: "Yellow cards received",
	},
	{
		key: "R",
		displayName: "red cards",
		singular: "red card",
		plural: "red cards",
		aliases: ["red", "reds", "sending off", "sendings off", "dismissal", "dismissals"],
		description: "Red cards received",
	},
	{
		key: "SAVES",
		displayName: "saves",
		singular: "save",
		plural: "saves",
		aliases: ["save", "stopping", "stopped", "blocked"],
		description: "Saves made (goalkeeper)",
	},
	{
		key: "OG",
		displayName: "own goals",
		singular: "own goal",
		plural: "own goals",
		aliases: ["own goal", "own goals", "scored against", "scored on own team"],
		description: "Own goals scored",
	},
	{
		key: "C",
		displayName: "conceded goals",
		singular: "goal conceded",
		plural: "goals conceded",
		aliases: ["conceded", "conceding", "let in", "allowed", "goals against"],
		description: "Goals conceded (team)",
	},
	{
		key: "CLS",
		displayName: "clean sheets",
		singular: "clean sheet",
		plural: "clean sheets",
		aliases: ["clean sheet", "clean sheets", "shutout", "shutouts", "no goals conceded"],
		description: "Clean sheets kept",
	},
	{
		key: "PSC",
		displayName: "penalties scored",
		singular: "penalty scored",
		plural: "penalties scored",
		aliases: ["penalty scored", "penalties scored", "penalty goal", "penalty goals", "spot kick goal"],
		description: "Penalties successfully converted",
	},
	{
		key: "PM",
		displayName: "penalties missed",
		singular: "penalty missed",
		plural: "penalties missed",
		aliases: ["penalty missed", "penalties missed", "penalty failure", "penalty failures", "spot kick miss"],
		description: "Penalties missed",
	},
	{
		key: "PCO",
		displayName: "penalties conceded",
		singular: "penalty conceded",
		plural: "penalties conceded",
		aliases: ["penalty conceded", "penalties conceded", "gave away penalty", "gave away penalties"],
		description: "Penalties conceded to opposition",
	},
	{
		key: "PSV",
		displayName: "penalties saved",
		singular: "penalty saved",
		plural: "penalties saved",
		aliases: ["penalty saved", "penalties saved", "stopped penalty", "stopped penalties"],
		description: "Penalties saved (goalkeeper)",
	},
	{
		key: "FTP",
		displayName: "fantasy points",
		singular: "fantasy point",
		plural: "fantasy points",
		aliases: ["fantasy point", "fantasy points", "fpl points", "fpl point", "fantasy football points"],
		description: "Fantasy football points earned",
	},
	{
		key: "TOTW",
		displayName: "team of the week",
		singular: "team of the week",
		plural: "teams of the week",
		aliases: ["team of the week", "teams of the week", "weekly totw", "weekly team of the week", "weekly selection"],
		description: "Weekly team of the week selections",
	},
	{
		key: "SEASON_TOTW",
		displayName: "season team of the week",
		singular: "season team of the week",
		plural: "season teams of the week",
		aliases: ["season totw", "season team of the week", "season selection", "yearly totw"],
		description: "Season team of the week selections",
	},
	{
		key: "POTM",
		displayName: "player of the month",
		singular: "player of the month",
		plural: "players of the month",
		aliases: ["player of the month", "players of the month", "monthly player", "monthly award"],
		description: "Player of the month awards",
	},
	{
		key: "CAPTAIN",
		displayName: "captain awards",
		singular: "captain award",
		plural: "captain awards",
		aliases: ["captain award", "captain awards", "captaincy", "captain selection"],
		description: "Captain awards and selections",
	},
	{
		key: "CO_PLAYERS",
		displayName: "co-players",
		singular: "co-player",
		plural: "co-players",
		aliases: ["co-player", "co-players", "teammates", "played with", "team mates"],
		description: "Players who have played together",
	},
	{
		key: "OPPONENTS",
		displayName: "opponents",
		singular: "opponent",
		plural: "opponents",
		aliases: ["opponent", "opponents", "played against", "faced", "versus"],
		description: "Opponents played against",
	},
	// Additional metrics for comprehensive testing
	{
		key: "AllGSC",
		displayName: "goals",
		singular: "goal",
		plural: "goals",
		aliases: ["goal", "scored", "scoring", "strikes"],
		description: "All goals scored",
	},
	{
		key: "GperAPP",
		displayName: "goals per appearance",
		singular: "goal per appearance",
		plural: "goals per appearance",
		aliases: ["goals per app", "goals per game", "scoring rate"],
		description: "Goals scored per appearance",
	},
	{
		key: "CperAPP",
		displayName: "goals conceded per appearance",
		singular: "goal conceded per appearance",
		plural: "goals conceded per appearance",
		aliases: ["conceded per app", "conceded per game"],
		description: "Goals conceded per appearance",
	},
	{
		key: "MperG",
		displayName: "minutes per goal",
		singular: "minute per goal",
		plural: "minutes per goal",
		aliases: ["mins per goal", "time per goal"],
		description: "Minutes played per goal scored",
	},
	{
		key: "MperCLS",
		displayName: "minutes per clean sheet",
		singular: "minute per clean sheet",
		plural: "minutes per clean sheet",
		aliases: ["mins per clean sheet", "time per clean sheet"],
		description: "Minutes played per clean sheet",
	},
	{
		key: "FTPperAPP",
		displayName: "fantasy points per appearance",
		singular: "fantasy point per appearance",
		plural: "fantasy points per appearance",
		aliases: ["ftp per app", "fantasy per game"],
		description: "Fantasy points per appearance",
	},
	{
		key: "DIST",
		displayName: "distance travelled",
		singular: "distance travelled",
		plural: "distances travelled",
		aliases: ["distance", "travel", "miles"],
		description: "Distance travelled to games",
	},
	{
		key: "HomeGames",
		displayName: "home games",
		singular: "home game",
		plural: "home games",
		aliases: ["home", "home matches"],
		description: "Home games played",
	},
	{
		key: "HomeWins",
		displayName: "home wins",
		singular: "home win",
		plural: "home wins",
		aliases: ["home victories", "home success"],
		description: "Home games won",
	},
	{
		key: "HomeGames%Won",
		displayName: "home games percentage won",
		singular: "home game percentage won",
		plural: "home games percentage won",
		aliases: ["home win rate", "home success rate"],
		description: "Percentage of home games won",
	},
	{
		key: "AwayGames",
		displayName: "away games",
		singular: "away game",
		plural: "away games",
		aliases: ["away", "away matches"],
		description: "Away games played",
	},
	{
		key: "AwayWins",
		displayName: "away wins",
		singular: "away win",
		plural: "away wins",
		aliases: ["away victories", "away success"],
		description: "Away games won",
	},
	{
		key: "AwayGames%Won",
		displayName: "away games percentage won",
		singular: "away game percentage won",
		plural: "away games percentage won",
		aliases: ["away win rate", "away success rate"],
		description: "Percentage of away games won",
	},
	{
		key: "Games%Won",
		displayName: "games percentage won",
		singular: "game percentage won",
		plural: "games percentage won",
		aliases: ["win rate", "success rate", "overall win rate"],
		description: "Overall percentage of games won",
	},
	// Team-specific metrics
	{
		key: "1sApps",
		displayName: "1st team appearances",
		singular: "1st team appearance",
		plural: "1st team appearances",
		aliases: ["1s", "1st team", "first team"],
		description: "Appearances for 1st team",
	},
	{
		key: "2sApps",
		displayName: "2nd team appearances",
		singular: "2nd team appearance",
		plural: "2nd team appearances",
		aliases: ["2s", "2nd team", "second team"],
		description: "Appearances for 2nd team",
	},
	{
		key: "3sApps",
		displayName: "3rd team appearances",
		singular: "3rd team appearance",
		plural: "3rd team appearances",
		aliases: ["3s", "3rd team", "third team"],
		description: "Appearances for 3rd team",
	},
	{
		key: "4sApps",
		displayName: "4th team appearances",
		singular: "4th team appearance",
		plural: "4th team appearances",
		aliases: ["4s", "4th team", "fourth team"],
		description: "Appearances for 4th team",
	},
	{
		key: "5sApps",
		displayName: "5th team appearances",
		singular: "5th team appearance",
		plural: "5th team appearances",
		aliases: ["5s", "5th team", "fifth team"],
		description: "Appearances for 5th team",
	},
	{
		key: "6sApps",
		displayName: "6th team appearances",
		singular: "6th team appearance",
		plural: "6th team appearances",
		aliases: ["6s", "6th team", "sixth team"],
		description: "Appearances for 6th team",
	},
	{
		key: "7sApps",
		displayName: "7th team appearances",
		singular: "7th team appearance",
		plural: "7th team appearances",
		aliases: ["7s", "7th team", "seventh team"],
		description: "Appearances for 7th team",
	},
	{
		key: "8sApps",
		displayName: "8th team appearances",
		singular: "8th team appearance",
		plural: "8th team appearances",
		aliases: ["8s", "8th team", "eighth team"],
		description: "Appearances for 8th team",
	},
	{
		key: "MostPlayedForTeam",
		displayName: "most played for team",
		singular: "most played for team",
		plural: "most played for teams",
		aliases: ["most played team", "favorite team"],
		description: "Team played for most often",
	},
	{
		key: "NumberTeamsPlayedFor",
		displayName: "number of teams played for",
		singular: "number of teams played for",
		plural: "number of teams played for",
		aliases: ["teams count", "team count"],
		description: "Number of different teams played for",
	},
	// Team-specific goals
	{
		key: "1sGoals",
		displayName: "1st team goals",
		singular: "1st team goal",
		plural: "1st team goals",
		aliases: ["1s goals", "1st team scoring"],
		description: "Goals scored for 1st team",
	},
	{
		key: "2sGoals",
		displayName: "2nd team goals",
		singular: "2nd team goal",
		plural: "2nd team goals",
		aliases: ["2s goals", "2nd team scoring"],
		description: "Goals scored for 2nd team",
	},
	{
		key: "3sGoals",
		displayName: "3rd team goals",
		singular: "3rd team goal",
		plural: "3rd team goals",
		aliases: ["3s goals", "3rd team scoring"],
		description: "Goals scored for 3rd team",
	},
	{
		key: "4sGoals",
		displayName: "4th team goals",
		singular: "4th team goal",
		plural: "4th team goals",
		aliases: ["4s goals", "4th team scoring"],
		description: "Goals scored for 4th team",
	},
	{
		key: "5sGoals",
		displayName: "5th team goals",
		singular: "5th team goal",
		plural: "5th team goals",
		aliases: ["5s goals", "5th team scoring"],
		description: "Goals scored for 5th team",
	},
	{
		key: "6sGoals",
		displayName: "6th team goals",
		singular: "6th team goal",
		plural: "6th team goals",
		aliases: ["6s goals", "6th team scoring"],
		description: "Goals scored for 6th team",
	},
	{
		key: "7sGoals",
		displayName: "7th team goals",
		singular: "7th team goal",
		plural: "7th team goals",
		aliases: ["7s goals", "7th team scoring"],
		description: "Goals scored for 7th team",
	},
	{
		key: "8sGoals",
		displayName: "8th team goals",
		singular: "8th team goal",
		plural: "8th team goals",
		aliases: ["8s goals", "8th team scoring"],
		description: "Goals scored for 8th team",
	},
	{
		key: "MostScoredForTeam",
		displayName: "most scored for team",
		singular: "most scored for team",
		plural: "most scored for teams",
		aliases: ["most scoring team", "best scoring team"],
		description: "Team scored most goals for",
	},
	// Seasonal metrics
	{
		key: "2016/17Apps",
		displayName: "2016/17 season appearances",
		singular: "2016/17 season appearance",
		plural: "2016/17 season appearances",
		aliases: ["2016-17", "2016/17", "season 2016/17"],
		description: "Appearances in 2016/17 season",
	},
	{
		key: "2017/18Apps",
		displayName: "2017/18 season appearances",
		singular: "2017/18 season appearance",
		plural: "2017/18 season appearances",
		aliases: ["2017-18", "2017/18", "season 2017/18"],
		description: "Appearances in 2017/18 season",
	},
	{
		key: "2018/19Apps",
		displayName: "2018/19 season appearances",
		singular: "2018/19 season appearance",
		plural: "2018/19 season appearances",
		aliases: ["2018-19", "2018/19", "season 2018/19"],
		description: "Appearances in 2018/19 season",
	},
	{
		key: "2019/20Apps",
		displayName: "2019/20 season appearances",
		singular: "2019/20 season appearance",
		plural: "2019/20 season appearances",
		aliases: ["2017-20", "2019/20", "season 2019/20"],
		description: "Appearances in 2019/20 season",
	},
	{
		key: "2020/21Apps",
		displayName: "2020/21 season appearances",
		singular: "2020/21 season appearance",
		plural: "2020/21 season appearances",
		aliases: ["2020-21", "2020/21", "season 2020/21"],
		description: "Appearances in 2020/21 season",
	},
	{
		key: "2021/22Apps",
		displayName: "2021/22 season appearances",
		singular: "2021/22 season appearance",
		plural: "2021/22 season appearances",
		aliases: ["2021-22", "2021/22", "season 2021/22"],
		description: "Appearances in 2021/22 season",
	},
	{
		key: "NumberSeasonsPlayedFor",
		displayName: "number of seasons played for",
		singular: "number of seasons played for",
		plural: "number of seasons played for",
		aliases: ["seasons count", "season count"],
		description: "Number of different seasons played for",
	},
	// Seasonal goals
	{
		key: "2016/17Goals",
		displayName: "2016/17 season goals",
		singular: "2016/17 season goal",
		plural: "2016/17 season goals",
		aliases: ["2016-17 goals", "2016/17 goals", "season 2016/17 goals"],
		description: "Goals scored in 2016/17 season",
	},
	{
		key: "2017/18Goals",
		displayName: "2017/18 season goals",
		singular: "2017/18 season goal",
		plural: "2017/18 season goals",
		aliases: ["2017-18 goals", "2017/18 goals", "season 2017/18 goals"],
		description: "Goals scored in 2017/18 season",
	},
	{
		key: "2018/19Goals",
		displayName: "2018/19 season goals",
		singular: "2018/19 season goal",
		plural: "2018/19 season goals",
		aliases: ["2018-19 goals", "2018/19 goals", "season 2018/19 goals"],
		description: "Goals scored in 2018/19 season",
	},
	{
		key: "2019/20Goals",
		displayName: "2019/20 season goals",
		singular: "2019/20 season goal",
		plural: "2019/20 season goals",
		aliases: ["2019-20 goals", "2019/20 goals", "season 2019/20 goals"],
		description: "Goals scored in 2019/20 season",
	},
	{
		key: "2020/21Goals",
		displayName: "2020/21 season goals",
		singular: "2020/21 season goal",
		plural: "2020/21 season goals",
		aliases: ["2020-21 goals", "2020/21 goals", "season 2020/21 goals"],
		description: "Goals scored in 2020/21 season",
	},
	{
		key: "2021/22Goals",
		displayName: "2021/22 season goals",
		singular: "2021/22 season goal",
		plural: "2021/22 season goals",
		aliases: ["2021-22 goals", "2021/22 goals", "season 2021/22 goals"],
		description: "Goals scored in 2021/22 season",
	},
	{
		key: "MostProlificSeason",
		displayName: "most prolific season",
		singular: "most prolific season",
		plural: "most prolific seasons",
		aliases: ["best season", "top season", "highest scoring season"],
		description: "Season with most goals scored",
	},
	// Positional metrics
	{
		key: "GK",
		displayName: "goalkeeper appearances",
		singular: "goalkeeper appearance",
		plural: "goalkeeper appearances",
		aliases: ["gk", "goalkeeper", "keeper", "goalie"],
		description: "Appearances as goalkeeper",
	},
	{
		key: "DEF",
		displayName: "defender appearances",
		singular: "defender appearance",
		plural: "defender appearances",
		aliases: ["def", "defender", "defence", "defense"],
		description: "Appearances as defender",
	},
	{
		key: "MID",
		displayName: "midfielder appearances",
		singular: "midfielder appearance",
		plural: "midfielder appearances",
		aliases: ["mid", "midfielder", "center mid", "central midfielder"],
		description: "Appearances as midfielder",
	},
	{
		key: "FWD",
		displayName: "forward appearances",
		singular: "forward appearance",
		plural: "forward appearances",
		aliases: ["fwd", "forward", "striker", "attacker"],
		description: "Appearances as forward",
	},
	{
		key: "MostCommonPosition",
		displayName: "most common position",
		singular: "most common position",
		plural: "most common positions",
		aliases: ["favorite position", "main position", "primary position"],
		description: "Position played most often",
	},
];

export const getMetricConfig = (key: string): MetricConfig | undefined => {
	return metricConfigs.find((config) => config.key === key);
};

export const findMetricByAlias = (alias: string): MetricConfig | undefined => {
	const lowerAlias = alias.toLowerCase();
	return metricConfigs.find(
		(config) =>
			config.aliases.some((a) => a.toLowerCase() === lowerAlias) ||
			config.displayName.toLowerCase() === lowerAlias ||
			config.key.toLowerCase() === lowerAlias,
	);
};

export const getMetricDisplayName = (key: string, value: number): string => {
	// Import statObject dynamically to avoid circular dependencies
	const { statObject } = require('../../config/config');
	
	// First try to get wordedText from statObject
	if (statObject && statObject[key] && statObject[key].wordedText) {
		return statObject[key].wordedText;
	}
	
	// Fallback to original config system
	const config = getMetricConfig(key);
	if (!config) return key;

	return value === 1 ? config.singular : config.plural;
};
