// Test Configuration Interface
export interface TestConfig {
	key: string;
	metric: string;
	questionTemplate: string;
	responsePattern: RegExp;
	description: string;
}

// Comprehensive test configurations for chatbot testing
export const STAT_TEST_CONFIGS: TestConfig[] = [
	{
		key: "APP",
		metric: "appearances",
		questionTemplate: "How many appearances has {playerName} made?",
		responsePattern: /(\d+)/,
		description: "Appearances",
	},
	{
		key: "MIN",
		metric: "minutes",
		questionTemplate: "How many minutes of football has {playerName} played?",
		responsePattern: /(\d+)/,
		description: "Minutes",
	},
	{
		key: "MOM",
		metric: "mom",
		questionTemplate: "How many MoMs has {playerName} received?",
		responsePattern: /(\d+)/,
		description: "Man of the Match awards",
	},
	{
		key: "G",
		metric: "goals",
		questionTemplate: "How many goals has {playerName} scored from open play?",
		responsePattern: /(\d+)/,
		description: "Goals",
	},
	{
		key: "A",
		metric: "assists",
		questionTemplate: "How many assists has {playerName} achieved?",
		responsePattern: /(\d+)/,
		description: "Assists",
	},
	{
		key: "Y",
		metric: "yellowCards",
		questionTemplate: "How many yellow cards has {playerName} received?",
		responsePattern: /(\d+)/,
		description: "Yellow Cards",
	},
	{
		key: "R",
		metric: "redCards",
		questionTemplate: "How many red cards has {playerName} received?",
		responsePattern: /(\d+)/,
		description: "Red Cards",
	},
	{
		key: "SAVES",
		metric: "saves",
		questionTemplate: "How many saves has {playerName} made?",
		responsePattern: /(\d+)/,
		description: "Saves",
	},
	{
		key: "OG",
		metric: "ownGoals",
		questionTemplate: "How many own goals has {playerName} scored?",
		responsePattern: /(\d+)/,
		description: "Own Goals",
	},
	{
		key: "C",
		metric: "conceded",
		questionTemplate: "How many goals has {playerName} conceded?",
		responsePattern: /(\d+)/,
		description: "Goals Conceded",
	},
	{
		key: "CLS",
		metric: "cleanSheets",
		questionTemplate: "How many clean sheets has {playerName} achieved?",
		responsePattern: /(\d+)/,
		description: "Clean Sheets",
	},
	{
		key: "PSC",
		metric: "penaltiesScored",
		questionTemplate: "How many penalties has {playerName} scored?",
		responsePattern: /(\d+)/,
		description: "Penalties Scored",
	},
	{
		key: "PM",
		metric: "penaltiesMissed",
		questionTemplate: "How many penalties has {playerName} missed?",
		responsePattern: /(\d+)/,
		description: "Penalties Missed",
	},
	{
		key: "PCO",
		metric: "penaltiesConceded",
		questionTemplate: "How many penalties has {playerName} conceded?",
		responsePattern: /(\d+)/,
		description: "Penalties Conceded",
	},
	{
		key: "PSV",
		metric: "penaltiesSaved",
		questionTemplate: "How many penalties has {playerName} saved?",
		responsePattern: /(\d+)/,
		description: "Penalties Saved",
	},
	{
		key: "FTP",
		metric: "fantasyPoints",
		questionTemplate: "How many fantasy points does {playerName} have?",
		responsePattern: /(-?\d+)/,
		description: "Fantasy Points",
	},
	// Advanced Statistics
	{
		key: "AllGSC",
		metric: "allGoals",
		questionTemplate: "How many goals has {playerName} scored?",
		responsePattern: /(\d+)/,
		description: "All Goals Scored",
	},
	{
		key: "GperAPP",
		metric: "goalsPerAppearance",
		questionTemplate: "How many goals on average has {playerName} scored per appearance?",
		responsePattern: /(\d+(?:\.\d+)?)/,
		description: "Goals per Appearance",
	},
	{
		key: "CperAPP",
		metric: "concededPerAppearance",
		questionTemplate: "How many goals on average does {playerName} concede per match?",
		responsePattern: /(\d+(?:\.\d+)?)/,
		description: "Goals Conceded per Appearance",
	},
	{
		key: "MperG",
		metric: "minutesPerGoal",
		questionTemplate: "How many minutes does it take on average for {playerName} to score?",
		responsePattern: /(\d+(?:\.\d+)?)/,
		description: "Minutes per Goal",
	},
	{
		key: "MperCLS",
		metric: "minutesPerCleanSheet",
		questionTemplate: "On average, how many minutes does {playerName} need to get a clean sheet?",
		responsePattern: /(\d+(?:\.\d+)?)/,
		description: "Minutes per Clean Sheet",
	},
	{
		key: "FTPperAPP",
		metric: "fantasyPointsPerAppearance",
		questionTemplate: "How many fantasy points does {playerName} score per appearance?",
		responsePattern: /(-?\d+(?:\.\d+)?)/,
		description: "Fantasy Points per Appearance",
	},
	{
		key: "DIST",
		metric: "distance",
		questionTemplate: "How far has {playerName} travelled to get to games?",
		responsePattern: /(\d+(?:\.\d+)?)/,
		description: "Distance Travelled",
	},
	// Home/Away Statistics
	{
		key: "HomeGames",
		metric: "homeGames",
		questionTemplate: "How many home games has {playerName} played?",
		responsePattern: /(\d+)/,
		description: "Home Games",
	},
	{
		key: "HomeWins",
		metric: "homeWins",
		questionTemplate: "How many home games has {playerName} won?",
		responsePattern: /(\d+)/,
		description: "Home Wins",
	},
	{
		key: "HomeGames%Won",
		metric: "homeGamesPercentWon",
		questionTemplate: "What percentage of home games has {playerName} won?",
		responsePattern: /(\d+(?:\.\d+)?)/,
		description: "Home Games % Won",
	},
	{
		key: "AwayGames",
		metric: "awayGames",
		questionTemplate: "How many away games has {playerName} played?",
		responsePattern: /(\d+)/,
		description: "Away Games",
	},
	{
		key: "AwayWins",
		metric: "awayWins",
		questionTemplate: "How many away games have {playerName} won?",
		responsePattern: /(\d+)/,
		description: "Away Wins",
	},
	{
		key: "AwayGames%Won",
		metric: "awayGamesPercentWon",
		questionTemplate: "What percent of away games has {playerName} won?",
		responsePattern: /(\d+(?:\.\d+)?)/,
		description: "Away Games % Won",
	},
	{
		key: "Games%Won",
		metric: "gamesPercentWon",
		questionTemplate: "What % of games has {playerName} won?",
		responsePattern: /(\d+(?:\.\d+)?)/,
		description: "Games % Won",
	},
	// Team-Specific Appearances
	{
		key: "1sApps",
		metric: "firstTeamApps",
		questionTemplate: "How many appearances has {playerName} made for the 1s?",
		responsePattern: /(\d+)/,
		description: "1st Team Appearances",
	},
	{
		key: "2sApps",
		metric: "secondTeamApps",
		questionTemplate: "How many apps has {playerName} made for the 2s?",
		responsePattern: /(\d+)/,
		description: "2nd Team Appearances",
	},
	{
		key: "3sApps",
		metric: "thirdTeamApps",
		questionTemplate: "How many times has {playerName} played for the 3s?",
		responsePattern: /(\d+)/,
		description: "3rd Team Appearances",
	},
	{
		key: "4sApps",
		metric: "fourthTeamApps",
		questionTemplate: "What is the appearance count for {playerName} playing for the 4s?",
		responsePattern: /(\d+)/,
		description: "4th Team Appearances",
	},
	{
		key: "5sApps",
		metric: "fifthTeamApps",
		questionTemplate: "How many games for the 5s has {playerName} played?",
		responsePattern: /(\d+)/,
		description: "5th Team Appearances",
	},
	{
		key: "6sApps",
		metric: "sixthTeamApps",
		questionTemplate: "How many appearances for the 6s has {playerName} made?",
		responsePattern: /(\d+)/,
		description: "6th Team Appearances",
	},
	{
		key: "7sApps",
		metric: "seventhTeamApps",
		questionTemplate: "How many apps for the 7s has {playerName} achieved?",
		responsePattern: /(\d+)/,
		description: "7th Team Appearances",
	},
	{
		key: "8sApps",
		metric: "eighthTeamApps",
		questionTemplate: "Provide me with {playerName} appearance count for the 8s.",
		responsePattern: /(\d+)/,
		description: "8th Team Appearances",
	},
	{
		key: "MostPlayedForTeam",
		metric: "mostPlayedForTeam",
		questionTemplate: "What team has {playerName} made the most appearances for?",
		responsePattern: /has made the most appearances for the (\d+s)/,
		description: "Most Played For Team",
	},
	{
		key: "NumberTeamsPlayedFor",
		metric: "numberTeamsPlayedFor",
		questionTemplate: "How many of the clubs teams has {playerName} played for?",
		responsePattern: /(\d+\/\d+)/,
		description: "Number of Teams Played For",
	},
	// Team-Specific Goals
	{
		key: "1sGoals",
		metric: "firstTeamGoals",
		questionTemplate: "How many goals has {playerName} scored for the 1s?",
		responsePattern: /(\d+)/,
		description: "1st Team Goals",
	},
	{
		key: "2sGoals",
		metric: "secondTeamGoals",
		questionTemplate: "What is the goal count of {playerName} for the 2nd team?",
		responsePattern: /(\d+)/,
		description: "2nd Team Goals",
	},
	{
		key: "3sGoals",
		metric: "thirdTeamGoals",
		questionTemplate: "How many goals in total has {playerName} scored for the 3s?",
		responsePattern: /(\d+)/,
		description: "3rd Team Goals",
	},
	{
		key: "4sGoals",
		metric: "fourthTeamGoals",
		questionTemplate: "How many goals have I scored for the 4s?",
		responsePattern: /(\d+)/,
		description: "4th Team Goals",
	},
	{
		key: "5sGoals",
		metric: "fifthTeamGoals",
		questionTemplate: "How many goals has {playerName} scored for the 5th XI?",
		responsePattern: /(\d+)/,
		description: "5th Team Goals",
	},
	{
		key: "6sGoals",
		metric: "sixthTeamGoals",
		questionTemplate: "What are the goal stats for {playerName} for the 6s?",
		responsePattern: /(\d+)/,
		description: "6th Team Goals",
	},
	{
		key: "7sGoals",
		metric: "seventhTeamGoals",
		questionTemplate: "How many goals have {playerName} got for the 7s?",
		responsePattern: /(\d+)/,
		description: "7th Team Goals",
	},
	{
		key: "8sGoals",
		metric: "eighthTeamGoals",
		questionTemplate: "How many goals has {playerName} scored for the 8s?",
		responsePattern: /(\d+)/,
		description: "8th Team Goals",
	},
	{
		key: "MostScoredForTeam",
		metric: "mostScoredForTeam",
		questionTemplate: "Which team has {playerName} scored the most goals for?",
		responsePattern: /has scored the most goals for the (\d+s)/,
		description: "Most Scored For Team",
	},
	// Seasonal Appearances
	{
		key: "2016/17Apps",
		metric: "season2016_17Apps",
		questionTemplate: "How many appearances did {playerName} make in the 2016/17 season?",
		responsePattern: /(\d+)/,
		description: "2016/17 Season Appearances",
	},
	{
		key: "2017/18Apps",
		metric: "season2017_18Apps",
		questionTemplate: "How many apps did {playerName} make in 2017/18?",
		responsePattern: /(\d+)/,
		description: "2017/18 Season Appearances",
	},
	{
		key: "2018/19Apps",
		metric: "season2018_19Apps",
		questionTemplate: "How many games did {playerName} play in in 2018-19?",
		responsePattern: /(\d+)/,
		description: "2018/19 Season Appearances",
	},
	{
		key: "2019/20Apps",
		metric: "season2019_20Apps",
		questionTemplate: "How many apps did {playerName} have in 2019/20?",
		responsePattern: /(\d+)/,
		description: "2019/20 Season Appearances",
	},
	{
		key: "2020/21Apps",
		metric: "season2020_21Apps",
		questionTemplate: "How many games did {playerName} appear in in 2020/21?",
		responsePattern: /(\d+)/,
		description: "2020/21 Season Appearances",
	},
	{
		key: "2021/22Apps",
		metric: "season2021_22Apps",
		questionTemplate: "How many appearances did {playerName} make in 2021 to 2022?",
		responsePattern: /(\d+)/,
		description: "2021/22 Season Appearances",
	},
	{
		key: "NumberSeasonsPlayedFor",
		metric: "numberSeasonsPlayedFor",
		questionTemplate: "How many seasons has {playerName} played in?",
		responsePattern: /(\d+)/,
		description: "Number of Seasons Played For",
	},
	// Seasonal Goals
	{
		key: "2016/17Goals",
		metric: "season2016_17Goals",
		questionTemplate: "How many goals did {playerName} score in the 2016/17 season?",
		responsePattern: /(\d+)/,
		description: "2016/17 Season Goals",
	},
	{
		key: "2017/18Goals",
		metric: "season2017_18Goals",
		questionTemplate: "How many goals did {playerName} score in the 2017-18 season?",
		responsePattern: /(\d+)/,
		description: "2017/18 Season Goals",
	},
	{
		key: "2018/19Goals",
		metric: "season2018_19Goals",
		questionTemplate: "How many goals did {playerName} get in the 2018/2019 season?",
		responsePattern: /(\d+)/,
		description: "2018/19 Season Goals",
	},
	{
		key: "2019/20Goals",
		metric: "season2019_20Goals",
		questionTemplate: "How many goals did {playerName} score in 2019/20?",
		responsePattern: /(\d+)/,
		description: "2019/20 Season Goals",
	},
	{
		key: "2020/21Goals",
		metric: "season2020_21Goals",
		questionTemplate: "How many goals did {playerName} score in the 20/21 season?",
		responsePattern: /(\d+)/,
		description: "2020/21 Season Goals",
	},
	{
		key: "2021/22Goals",
		metric: "season2021_22Goals",
		questionTemplate: "How many goals did {playerName} score in 21/22?",
		responsePattern: /(\d+)/,
		description: "2021/22 Season Goals",
	},
	{
		key: "MostProlificSeason",
		metric: "mostProlificSeason",
		questionTemplate: "What was {playerName}'s most prolific season?",
		responsePattern: /([A-Za-z0-9\-\/]+)/,
		description: "Most Prolific Season",
	},
	// Positional Statistics
	{
		key: "GK",
		metric: "goalkeeperApps",
		questionTemplate: "How many times has {playerName} played as a goalkeeper?",
		responsePattern: /(\d+)/,
		description: "Goalkeeper Appearances",
	},
	{
		key: "DEF",
		metric: "defenderApps",
		questionTemplate: "How many games has {playerName} played as a defender?",
		responsePattern: /(\d+)/,
		description: "Defender Appearances",
	},
	{
		key: "MID",
		metric: "midfielderApps",
		questionTemplate: "How many times has {playerName} been a midfielder?",
		responsePattern: /(\d+)/,
		description: "Midfielder Appearances",
	},
	{
		key: "FWD",
		metric: "forwardApps",
		questionTemplate: "How many games has {playerName} been a forward?",
		responsePattern: /(\d+)/,
		description: "Forward Appearances",
	},
	{
		key: "MostCommonPosition",
		metric: "mostCommonPosition",
		questionTemplate: "What is {playerName}'s most common position played?",
		responsePattern: /([A-Za-z]+)/,
		description: "Most Common Position",
	},
];